### ISSUE TITLE
Cannot install package for net462 project on VS2017 

### ISSUE THREAD

**Issue by hcoona** [rmc00/Maybe#1]
Environment:
* Windows 10
* Visual Studio 2017
* C# project with framework 4.6.2
* Maybe.Net v1.0.77

Error Message: (Sorry for Chinese locale, the main meaning is the package not compatible with net462)

> 正在还原 D:\GitProjects\BigsetExisting\BigsetExisting\BigsetExisting.csproj 的包...
> 包 Maybe.NET 1.0.77 与 net462 (.NETFramework,Version=v4.6.2) 不兼容。 包 Maybe.NET 1.0.77 支持: release (Release,Version=v0.0)
> 包 Maybe.NET 1.0.77 与 net462 (.NETFramework,Version=v4.6.2) / win 不兼容。 包 Maybe.NET 1.0.77 支持: release (Release,Version=v0.0)
> 包 Maybe.NET 1.0.77 与 net462 (.NETFramework,Version=v4.6.2) / win-x64 不兼容。 包 Maybe.NET 1.0.77 支持: release (Release,Version=v0.0)
> 包 Maybe.NET 1.0.77 与 net462 (.NETFramework,Version=v4.6.2) / win-x86 不兼容。 包 Maybe.NET 1.0.77 支持: release (Release,Version=v0.0)
> 程序包还原失败。正在回滚“BigsetExisting”的程序包更改。
> 已用时间: 00:00:00.2589401

Reproduce steps:
1. New Console project with net framework 4.6.2
2. Manage NuGet package
3. Find & Add "Maybe.Net 1.0.77"

**Comment by hcoona** [comment]
I'm able to reference your project by source code.

**Comment by rmc00** [comment]
Thanks for making the fix.
