### ISSUE TITLE
XML Documentation

### ISSUE THREAD

**Issue by RomanKreisel** [rmc00/Maybe#7]
I saw, that most methods already have XML Documentation written for them.
Unfortunately, they're not distributed via NuGet. Doing this would make it much easier for developers to use this library:

https://stackoverflow.com/questions/5205738/how-do-you-include-xml-docs-for-a-class-library-in-a-nuget-package

**Comment by rmc00** [comment]
Thanks for this suggestion -- it's a another great addition that can improve the library without requiring much effort, so I went ahead and tried to get it done right away. I'm not sure that all the documentation is as good as it could be, but it's definitely better than nothing. I was already planning to review the existing data structures for test coverage and see if I could get better tests on them at scale -- I'll make sure I review the XML documentation as part of that process too. At least this is a start though!
